# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Christina Yoka"                                # Your name
  description: "Christina is an Environmental and Community Health Advocate"   # A brief slogan (optional)
  image: img/Christina_Guyana.jpg
  
  navbar:
    pinned: true
    logo: /img/flower.png
    
    left:
      - text: "Education"
        href: Education/index.qmd
      - text: "Professional"
        href: cv/index.qmd
    
    
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/christina-yoka-46076015/
      - icon: envelope
        aria-label: email
        href: "mailto:cxy533@case.edu"  
  
  # Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block"><a href="https://www.linkedin.com/in/christina-yoka-46076015/">Connect with me on LinkedIn!</a></span>
    
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true